version: "3.9"
services:
  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000/tcp"
    volumes:
      - ./configs/blocky-config.yml:/app/config.yml
  heimdall:
    image: "linuxserver/heimdall"
    container_name: heimdall
    restart: unless-stopped
    ports:
      - "8006:80/tcp"
      - "406:443/tcp"
    volumes:
      - ./configs:/config
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/ec/localtime:ro
      - ./configs:/config
  octoprint:
    image: octoprint/octoprint
    container_name: octoprint
    restart: unless-stopped
    ports:
      - "5000:80/tcp"
#    devices:
#      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - ./configs:/config
