version: "3.9"
services:
  influxdb:
    image: "influxdb:2.0"
    container_name: "influxdb"
    restart: unless_stopped
    ports:
      - "8086:8086/tcp"
    volumes:
      - $HOME/influxdbv2:/root/.influxdbv2